# Generated by Django 4.0.2 on 2022-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_remove_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
